version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "10:00"
    timezone: America/New_York
  open-pull-requests-limit: 100
  registries: "*"
